POST http://localhost:5031/api/product/get
Content-Type: application/json

{
    "id": "26643622-392e-4042-83aa-75e842021b72",
    "name": "Small Soft Chips"
}

###

POST http://localhost:5031/api/product/get
Content-Type: application/json

{
    "id": "4eebe635-c061-45a8-9912-e78180fd22bb",
    "name": "Practical Plastic Ball"
}

