POST http://localhost:5031/api/order/
Content-Type: application/json


{
    "CustomerId": "cbe2866e-1b7c-4d33-9dd5-5b5a5803325f",
    "orderProducts": [
        {
            "productId": "84a5299e-3f3f-4d18-a17c-0e1d95d59a97",
            "quantity": 2            
        },
        {
            "productId": "f07c874d-97a8-436c-9cc2-7c24708bfe1b",
            "quantity": 1            
        }
    ],
    "totalToPay": 30.00
}