// <auto-generated />
using System;
using DI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DependencyInjection.Migrations
{
    [DbContext(typeof(DIDbContext))]
    partial class DIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DI.Domain.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MathOperation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("DIEF.Models.OperationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("LeftNumber")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Result")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RightNumber")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.ToTable("OperationResults");
                });

            modelBuilder.Entity("DIEF.Models.OperationResult", b =>
                {
                    b.HasOne("DI.Domain.Operation", "Operation")
                        .WithOne("OperationResult")
                        .HasForeignKey("DIEF.Models.OperationResult", "OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("DI.Domain.Operation", b =>
                {
                    b.Navigation("OperationResult");
                });
#pragma warning restore 612, 618
        }
    }
}
