POST http://localhost:5031/api/order/products
Content-Type: application/json

{
    "productId": "4eebe635-c061-45a8-9912-e78180fd22bb",
    "orderId": "4acc3d05-138d-46ea-a85f-d35ed1519ecc",
    "quantity": 0,
    "total": 10.00
}

### 

POST http://localhost:5031/api/order/products
Content-Type: application/json

{
    "productId": "1b208beb-27cb-45ef-8e72-29a061fc239a",
    "orderId": "4acc3d05-138d-46ea-a85f-d35ed1519ecc",
    "quantity": 1,
    "total": 10.00
}

###

POST http://localhost:5031/api/order/products
Content-Type: application/json

{    
    "productId": "1526a84f-5e0f-4103-be98-54e3b325a8b0",
    "orderId": "4acc3d05-138d-46ea-a85f-d35ed1519ecc",
    "quantity": 1,
    "total": 10.00
}

###

POST http://localhost:5031/api/order/products
Content-Type: application/json

{    
    "productId": "9edac144-72d0-487a-9fd5-6cd5e626075d",
    "orderId": "4acc3d05-138d-46ea-a85f-d35ed1519ecc",
    "quantity": 1,
    "total": 10.00
}

