POST http://localhost:5031/api/order/new
Content-Type: application/json

{
    "CustomerId": "16692fc1-acd0-4c84-9360-f3c628d10e62",
    "orderProducts": [
        {
            "productId": "01d36197-f384-42c4-85ac-2ccad677fea4",
            "quantity": 1
        },
        {
            "productId": "02853b1e-d5b5-4c42-88e6-8db826d9157b",
            "quantity": 1
        }
    ],
    "coupon": {
        "code": "black friday"
    }
}

###

POST http://localhost:5031/api/order/new
Content-Type: application/json

{
    "CustomerId": "0584cdbf-21e2-4411-b74f-d68cafd1c726",
    "orderProducts": [
        {
            "productId": "01d36197-f384-42c4-85ac-2ccad677fea4",
            "quantity": 1
        },
        {
            "productId": "02853b1e-d5b5-4c42-88e6-8db826d9157b",
            "quantity": 2
        },
        {
            "productId": "fc9b0623-c63d-4992-b33d-a040a400cc6b",
            "quantity": 1
        },
        {
            "productId": "fc1669b0-bd7b-4564-9d0f-efcdaaa6ffbf",
            "quantity": 3
        }
    ],
    "coupm": {
        "code": "black friday"
    }
}