POST http://localhost:5031/api/product/product
Content-Type: application/json

{
    "id": "13aa205a-6f8f-43fd-80cd-9e8fbaf770bf"
}

###

POST http://localhost:5031/api/product/product
Content-Type: application/json

{
    "id": "002a5c2c-96d9-4d6b-8e33-d9af20bad573"
}

