POST http://localhost:5031/api/order/products
Content-Type: application/json

{
    "productId": "ee26bd9b-ad8e-4cc7-9443-c295268050b8",
    "orderId": "71a5b607-ff2b-4a2f-8d1c-91d95b95b754",
    "quantity": 2
}

###

POST http://localhost:5031/api/order/products
Content-Type: application/json

{
    "productId": "fd6c7b81-4138-4427-8de8-9ae0c91e9b4b",
    "orderId": "db2981c3-f7ba-4190-b65c-424a2823eff2",
    "quantity": 1
}

###

POST http://localhost:5031/api/order/products
Content-Type: application/json

{
    "productId": "1526a84f-5e0f-4103-be98-54e3b325a8b0",
    "orderId": "974e7ec8-d412-4583-96d0-c153787d85aa",
    "quantity": 1
}

###

POST http://localhost:5031/api/order/products
Content-Type: application/json

{
    "productId": "ee3ae602-7490-451f-948b-ec0b02391154",
    "orderId": "974e7ec8-d412-4583-96d0-c153787d85aa",
    "quantity": 1
}

